### ISSUE TITLE
Crash on large repo with many solutions

### ISSUE THREAD

**Issue by brumlemann** [JocysCom/VsReferenceManager#1]
Hi,

Subject says it all I guess. I will clone this repo and see if I can figure out where things go wrong but I don't have all the time in the world so suggestions are welcome.

What happens is that I add the folder inside the repo with all my projects (close to 600). I ahve already prepared a solution with all the project in them (easy PS script).

When I click Scan it begins and then after a short while my VS instance suddenly dies. Here is the call stack from the event viewer:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Build.Exceptions.InvalidProjectFileException
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean, System.String, Microsoft.Build.Shared.BuildEventFileInfo, System.Exception, System.String, System.Object[])
   at Microsoft.Build.Construction.SolutionFile.ParseSolution()
   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()
   at Microsoft.Build.Construction.SolutionFile.Parse(System.String)
   at JocysCom.VS.ReferenceManager.LocationsScanner.ParseSolutionFile(System.String)
   at JocysCom.VS.ReferenceManager.LocationsScanner.Scan(System.String[], System.Collections.Generic.IList`1<JocysCom.VS.ReferenceManager.ProjectFileInfo>, System.String)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

I know there are "invalid projects" inside the solution (old stuff that we want to use the new solution to get under control and clean out), but it shouldn't bring down the whole extension and VS with it. The good solution would probably be to just ignore the invalid projects.

Regards
M

**Comment by brumlemann** [comment]
Figured that one out. There are Web Site projects and they end up with a solutionProject here

https://github.com/JocysCom/VsReferenceManager/blob/b7abd9ee05d91eb9e6824aea69dcc34e2cbb3bc3/ReferenceManager/Common/LocationsScanner.cs#L206

with a .RelativePath that begins with "http://", which then feails on subsequent Path.Combine() because it's not a legal path.

So I am testing out with

` 
foreach (var solutionProject in solutionProjects.Where(sp=>!sp.RelativePath.Contains("http://")))
   {
        var fullName = Path.Combine(ri.SolutionPath, solutionProject.RelativePath);
`

**Comment by EJocys** [comment]
@brumlemann

Thank you for reporting this issue and for figuring out solution. Updated code according to your suggestion, and released new version (1.12) on https://marketplace.visualstudio.com/items?itemName=JocysCom.JocysComVsReferenceManager

I will try to do more tests with different web projects later. Please, let me know if problem still exists in 1.12.

Kind regards,
Evaldas Jocys
